# Benchmark Configuration
# =====================

# Environment settings
grid_size: 4
max_steps: 1000
visualization: false  # Disable visualization for benchmarking
random_seed: 42
green_duration: 10

# Traffic patterns
traffic_patterns:
  uniform:
    north_south_rate: 0.3
    east_west_rate: 0.3
  rush_hour:
    north_south_rate: 0.6
    east_west_rate: 0.3

# Agent settings
agent:
  dqn:
    learning_rate: 0.0005
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    buffer_size: 50000
    batch_size: 128
    hidden_dim: 128
    target_update: 10
    update_every: 4
    device: "auto"
    
  simple_dqn:
    learning_rate: 0.0005
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    buffer_size: 50000
    batch_size: 128
    hidden_dim: 128
    target_update: 10
    update_every: 4
    device: "auto"
    
  ppo:
    learning_rate: 0.0003
    gamma: 0.99
    gae_lambda: 0.95
    clip_epsilon: 0.2
    c1: 0.5
    c2: 0.01
    batch_size: 64
    n_epochs: 4
    hidden_dim: 128
    device: "auto"

# Training settings
num_episodes: 500
eval_frequency: 100
save_frequency: 100
early_stopping_patience: 20
early_stopping_reward: 10000

# Reward function settings
waiting_time_weight: -1.0
throughput_weight: 1.0
max_waiting_time: 100
reward_scale: 0.01

# Output settings
model_dir: "results/benchmark"
log_dir: "logs/benchmark"
visualization_dir: "visualizations/benchmark" 