# Benchmark Configuration
# =====================

# Environment settings
grid_size: 4
max_steps: 1000
visualization: false  # Disable visualization for benchmarking
random_seed: 42
green_duration: 1
max_cars: 200         # Maximum cars per lane (increased from 100)
max_active_cars: 500  # Maximum active cars total (increased from 300)
car_spawn_probability: 0.6  # Higher probability to generate more cars (increased from 0.4)

# Model architecture settings
use_per_intersection: true  # Enable per-intersection control
hidden_dim: 128

# Traffic patterns
traffic_patterns:
  uniform:
    north_south_rate: 0.4  # Increased from 0.3
    east_west_rate: 0.4    # Increased from 0.3
  rush_hour:
    north_south_rate: 0.8  # Increased from 0.6
    east_west_rate: 0.5    # Increased from 0.3

# Agent settings
agent:
  dqn:
    learning_rate: 0.0005
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    buffer_size: 50000
    batch_size: 128
    hidden_dim: 128
    target_update: 10
    update_every: 4
    device: "mps"  # Changed from "auto" to "mps" for Mac acceleration
    use_per_intersection: true
    
  simple_dqn:
    learning_rate: 0.0005
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    buffer_size: 50000
    batch_size: 128
    hidden_dim: 128
    target_update: 10
    update_every: 4
    device: "mps"  # Changed from "auto" to "mps" for Mac acceleration
    use_per_intersection: true
    
  ppo:
    learning_rate: 0.0003
    gamma: 0.99
    gae_lambda: 0.95
    clip_epsilon: 0.2
    c1: 0.5
    c2: 0.01
    batch_size: 64
    n_epochs: 4
    hidden_dim: 128
    device: "mps"  # Changed from "auto" to "mps" for Mac acceleration
    use_per_intersection: true

# Training settings
num_episodes: 500
eval_frequency: 100
save_frequency: 100
early_stopping_patience: 20
early_stopping_reward: 10000

# Reward function settings
waiting_time_weight: -1.0
throughput_weight: 1.0
max_waiting_time: 100
reward_scale: 0.01
use_normalized_reward: false

# Output settings
model_dir: "results/benchmark"
log_dir: "logs/benchmark"
visualization_dir: "visualizations/benchmark" 