# Default configuration for Traffic RL

# Environment settings
environment:
  num_intersections: 1
  max_steps: 1000
  observation_type: "state"  # Options: state, image
  reward_type: "waiting_time"  # Options: waiting_time, queue_length, throughput
  traffic_pattern: "uniform"  # Options: uniform, rush_hour, variable

# Agent settings
agent:
  type: "dqn"  # Options: dqn, fixed_timing, adaptive_timing, random
  hidden_size: 128
  learning_rate: 0.001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  memory_size: 10000
  batch_size: 32
  target_update: 10

# Training settings
training:
  num_episodes: 1000
  eval_interval: 100
  save_interval: 100
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

# Visualization settings
visualization:
  render: false
  save_plots: true
  plot_interval: 100 